contact_links:
  - name: Discord
    url: https://discord.gg/FKcURWZsMW
    about: "Присоединяйтесь к нашему Discord-сообществу."
  - name: Telegram
    url: https://t.me/krpgd
    about: "Следите за обновлениями в Telegram."
