name: Release

on:
  push:
    tags:
      - 'v*'  # Срабатывает при пуше тегов типа v1.2.3

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install tools
        run: |
          pip install tomli
          cargo install git-cliff

      - name: Check version match
        run: |
          VERSION_IN_TAG=${GITHUB_REF##*/}        # v1.2.3
          VERSION_IN_FILE=$(python -c "import tomli; print(tomli.load(open('pyproject.toml', 'rb'))['project']['version'])")
          if [ "$VERSION_IN_TAG" != "v$VERSION_IN_FILE" ]; then
            echo "Version mismatch: tag $VERSION_IN_TAG vs file $VERSION_IN_FILE"
            exit 1
          fi
          
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          body_path: CHANGELOG.md
